version: 1.8.{build}
image: Visual Studio 2017


platform:
    - Any CPU

configuration:
    - Release
    - Debug

install:
    - ps: >-
        Start-FileDownload 'https://github.com/EWSoftware/SHFB/releases/download/v2019.9.15.0/SHFBInstaller_v2019.9.15.0.zip'

        7z x -y SHFBInstaller_v2019.9.15.0.zip | Out-Null

        Write-Host "Installing MSI..."

        cmd /c start /wait msiexec /i InstallResources\SandcastleHelpFileBuilder.msi /quiet

        Write-Host "Installing VSIX..."

        . "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VSIXInstaller.exe" /q /a InstallResources\SHFBVisualStudioPackage_VS2015AndLater.vsix

        Write-Host "Sandcastle installed" -ForegroundColor Green

build_script:
    - set SHFBROOT=C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - msbuild MediaDevices.sln /m /verbosity:minimal /t:restore /p:configuration="%configuration%" /p:platform="%platform%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    - msbuild MediaDevices.sln /m /verbosity:minimal /p:configuration="%configuration%" /p:platform="%platform%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    - cd "%APPVEYOR_BUILD_FOLDER%"\MediaDevices
    - pack.cmd

# after_build:
    # - cd "%APPVEYOR_BUILD_FOLDER%"
    # - ps: >-
        # Push-AppveyorArtifact "MediaDevices\bin\$env:CONFIGURATION\MediaDevices.dll" -FileName MediaDevices.dll

        # if ($($env:APPVEYOR_REPO_TAG) -eq "true" -and $env:CONFIGURATION -eq "Release") {
            # $ZipFileName = "MediaDevices_$($env:APPVEYOR_REPO_TAG_NAME).zip"
            # 7z a $ZipFileName MediaDevices\bin\$env:CONFIGURATION\MediaDevices.dll
        # }

# artifacts:
  # - path: MediaDevices_*.zip
    # name: releases

# deploy:
    # provider: GitHub
    # auth_token:
        # secure: !!TODO, see https://www.appveyor.com/docs/deployment/github/#provider-settings!!
    # artifact: releases
    # draft: false
    # prerelease: false
    # force_update: true
    # on:
        # appveyor_repo_tag: true
        # configuration: Release
