name: Continuous Integration 2019

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2019
    strategy:
      max-parallel: 2
      matrix:
        build_configuration: [Release, Debug]
      
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.3

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    - name: Install SHFB
      uses: Bassman2/setup-SHFB@v1
      with:
        version: v2021.11.7.0

    - name: Copy dummy key for signing
      run: |
           Copy-Item  DummySignKey.snk -Destination Src\MediaDevices60\Bassman.snk
           Copy-Item  DummySignKey.snk -Destination Src\MediaDevices50\Bassman.snk
           Copy-Item  DummySignKey.snk -Destination Src\MediaDevicesCore31\Bassman.snk
           Copy-Item  DummySignKey.snk -Destination Src\MediaDevicesCore21\Bassman.snk
           Copy-Item  DummySignKey.snk -Destination Src\MediaDevicesFramework48\Bassman.snk
           Copy-Item  DummySignKey.snk -Destination Src\MediaDevicesFramework45\Bassman.snk
           Copy-Item  DummySignKey.snk -Destination Src\MediaDevicesFramework40\Bassman.snk

    - name: Nuget restore solution
      run: nuget restore MediaDevices19.sln

    - name: MSBuild of solution
      run: msbuild MediaDevices19.sln /p:configuration="${{ matrix.build_configuration }}" /m /verbosity:minimal
