name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022
    environment: sign
    strategy:
      max-parallel: 2
      matrix:
        build_configuration: [Release, Debug]
      
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    - name: Add SignKeys
      uses: Bassman2/SignKey@v1
      with:
        file: Bassman.snk
        key: ${{ secrets.SIGNKEY }}
        
    - name: Install SHFB
      uses: Bassman2/setup-SHFB@v1
      with:
        version: 2022.12.30.0

    - name: Nuget restore solution
      run: nuget restore MediaDevices.sln

    - name: Dotnet restore solution
      run: dotnet restore MediaDevices.sln

    - name: MSBuild of solution
      run: msbuild MediaDevices.sln /p:configuration="${{ matrix.build_configuration }}" /m /verbosity:minimal
      env:
        SHFBROOT: C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\